name: Publish Docker image to GHCR
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REPO_PATH }}:${{ env.VERSION }} .
          docker tag ${{ env.REPO_PATH }}:${{ env.VERSION }} ${{ env.REPO_PATH }}:latest
          docker push ${{ env.REPO_PATH }}:${{ env.VERSION }}
          docker push ${{ env.REPO_PATH }}:latest


