name: Validate Tag

on:
  push:
    tags:
      - '*'
  workflow_call:

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate tag matches package.json version
        run: |
          TAG="${{ github.ref_name }}"
          PKG_VERSION=$(jq -r .version package.json)
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "Tag ($TAG) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi
